---

width: 640
height: 640

pin_length: 6
n_more_probable_pins: 20


ModelWrapper:
  phone_seg_weights: 'resources/weights/yolov8-segm-2-phone.pt'
  smudges_det_weights: 'resources/weights/yolov8-detx-2-smudges.pt'

  interp_step: 25                   # interpolation of segmented line


DigitRecognition:
  canny_thresholds: [200, 255]      # [lower, upper] thresholds for Canny edge detection
  cluster_eps: 10                   # DBSCAN clustering epsilon
  cluster_min_samples: 20           # DBSCAN clustering min_samples
  bounds: [0.1, 0.9]                # [lower, upper] inner bounds for digit recognition
  digit_alignment_iter: 5           # number of iterations to ensure good enough cipher matrix recognition (1 to 9)
  digit_alignment_delta: [20, 20]   # [x, y] in pixels for matrix digits alignment
  bbox_padding: [50, 35]            # [w, h] bbox padding in pixels (applied to all sides)

CipherGuessing:
  min_iou: 0.3                      # minimum IOU for cipher guessing


OrderGuessing:
  # '###' will be replaced with the pin length's literal
  transition_matrix: 'resources/stats/###_symbols/markovChainTransitionMatDump'
  prob_by_index: 'resources/stats/###_symbols/probByIndexDump'
  frequencies: 'resources/stats/###_symbols/frequenciesDump'

...